apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: frontend
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      service: frontend
  template:
    metadata:
      labels:
        service: frontend
    spec:
      containers:
      - image: khanhtruong126/udagram-frontend:v1
        name: frontend
        imagePullPolicy: Always
        ports:
        - containerPort: 80