apiVersion: v1
kind: Service
metadata:
  name: reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      service: reverseproxy
  template:
    metadata:
      labels: 
        service: reverseproxy
    spec:
      containers:
      - name: reverseproxy
        image: khanhtruong126/reverseproxy:v1
        imagePullPolicy: Always
        port:
        - containerPort: 80
        resources: 
          limits: 
            cpu: 1000m
          requests:
            cpu: 500m

